---

  - hosts: Gopher-dev
    gather_facts: False
    remote_user: ctummalachervu
    become: yes


    vars:
      - packages: ["git"]
    tasks:
      - name: Installing {{ packages }} on Gopher Server
        yum:
          name: "{{ item }}"
          state: present
        with_items: "{{ packages }}"